apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: codegen-0603-3 
  janus-idp.io/tekton: codegen-0603-3
  backstage.io/kubernetes-id: codegen-0603-3
  backstage.io/kubernetes-namespace: rhtap-app-development 
  app.kubernetes.io/part-of: codegen-0603-3
resources: 
- application-dev.yaml